---
- name: add users
  hosts: all 
  user: root
  vars:
    users: 
      - ben
      - lisa
      - kate
      - dan
      - sam
  tasks:
  - name: add list of users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa
    with_items: "{{ users }}"
    