- name: Add users
  hosts: all
  become: yes
  become_method: root
  tasks:
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: "{{ item }}"
      with_items:
      - ugur
      - fadime
      - oyku