---
- name: Petclinic App Installation
  hosts: all
  user: root
  tasks: 
  - name: Pull Petclinic Repository
    git:
      repo: https://github.com/spring-projects/spring-petclinic.git
      version: main
      dest: /var/www/spring-petclinic/
  
  - name: PWD Command
    ansible.builtin.shell:
      cmd: pwd