---
- name: Petclinic App Installation
  hosts: all
  user: root
  tasks: 
  - name: Pull Petclinic Repository
    git:
      repo: https://github.com/spring-projects/spring-petclinic.git
      version: main
      dest: /spring-petclinic

  - name: Install Java
    yum:
      state: present
      name:
      - openjdk-11-jdk

  - name: Run mvn package command
    command: ./mvnw package
    args:
      chdir: /spring-petclinic

  - name: Run the java app
    command: java -jar target/*.jar
    args:
      chdir: /spring-petclinic









  # - name: PWD Command
  #   ansible.builtin.shell:
  #     cmd: pwd
  #   register: output

  # - name: Debug output
  #   debug:
  #     var: output

  